config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
    get "complete"
    get "active"

    collection do
      get 'filter'
    end
  end
  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  validates :status, :inclusion => { :in => ['Active', 'Complete'], message: 'Must be Active/Completed' } 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks.sort_by &:status
    @all_count = current_user.tasks.count
    @complete_count = current_user.tasks.where(:status => "Complete").count
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def complete
    @task = Task.find(params[:task_id])
    @task.update(:status => "Complete")
    @tasks = current_user.tasks.sort_by &:status
    @all_count = current_user.tasks.count
    @complete_count = current_user.tasks.where(:status => "Complete").count
    respond_to do |format|
      format.html { render :index}
      format.json { head :no_content }
    end
  end

  def active
    @task = Task.find(params[:task_id])
    @task.update(:status => "Active")
    @tasks = current_user.tasks.sort_by &:status
    @all_count = current_user.tasks.count
    @complete_count = current_user.tasks.where(:status => "Complete").count
    respond_to do |format|
      format.html { render :index}
      format.json { head :no_content }
    end
  end

  def filter
    @all_count = current_user.tasks.count
    @complete_count = current_user.tasks.where(:status => "Complete").count
    if(params[:type] == "All")
      @tasks = current_user.tasks.sort_by &:status
    else
      @tasks = current_user.tasks.where(:status => params[:type])
      @status = params[:type]
    end

    respond_to do |format|
      format.html { render :index}
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /tasks/
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:desc, :status, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>

<%= nav_bar fixed: :top, brand: "ToDo List" do %>
  <%= menu_group pull: :right do %>
      <%if (current_user)%>
          <%= menu_item "Logout", destroy_user_session_path, :style=>'font-weight: bold;', :method => :delete %>
      <% end %>
  <% end %>
<% end %>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { :class => "form-horizontal task" } do |f| %>

  <% if @task.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :desc, "Description", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :desc, :class => 'form-control' %>
    </div>
    <%=f.error_span(:desc) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2 hidden' %>
    <div class="col-lg-10">
      <%= f.hidden_field :status, :class => 'form-control', :value => "Active" %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2 hidden' %>
    <div class="col-lg-10">
      <%= f.hidden_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tasks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>


<%= form_for @task, :html => { :class => "form-horizontal task" } do |f| %>

  <% if @task.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :desc, "Description", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :desc, :class => 'form-control' %>
    </div>
    <%=f.error_span(:desc) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <% if @task.status == "Active" %>
        <%= f.radio_button :status, "Active", :checked => true%>
      <% else %>
        <%= f.radio_button :status, "Active" %>
      <% end %>
      <%= label_tag(:status_active, "Active") %>

      <% if @task.status == "Complete" %>
        <%=f.radio_button :status, "Complete", :checked => true%>
      <% else %>
        <%= f.radio_button :status, "Complete" %>
      <% end %>
      <%= label_tag(:status_complete, "Complete") %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2 hidden' %>
    <div class="col-lg-10">
      <%= f.hidden_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tasks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<div class="page-header" style = "background-image: url('/assets/bg.png'); background-size:20%; height: 80px;">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<div class = "row", style = "margin-bottom : 10px;" >
  <%= form_tag("/tasks/filter", method: "get") do %>
    <%= label_tag(:type, "Show:", :class => 'control-label col-lg-1') %>

    <% if @status.nil? %>
      <%= radio_button_tag(:type, "All", :checked => true)%>
    <% else %>
      <%= radio_button_tag(:type, "All")%>
    <% end %>
    <%= label_tag(:type_all, "All (#{@all_count})", :style => "margin-left: 3px; margin-right: 5px;") %>

    <% if @status == "Active" %>
      <%= radio_button_tag(:type, "Active", :checked => true)%>
    <% else %>
      <%= radio_button_tag(:type, "Active") %>
    <% end %>
    <%= label_tag(:type_active, "Active (#{@all_count-@complete_count})", :style => "margin-left: 3px; margin-right: 5px;") %>

    <% if @status == "Complete" %>
      <%= radio_button_tag(:type, "Complete", :checked => true)%>
    <% else %>
      <%= radio_button_tag(:type, "Complete") %>
    <% end %>
    <%= label_tag(:type_complete, "Complete (#{@complete_count})", :style => "margin-left: 3px; margin-right: 5px;") %>

    <%= submit_tag("Filter", :class => 'btn btn-default btn-xs', :style => "margin-left: 15px;" ) %>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Sl) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:added_on) %></th>
      <th><%= model_class.human_attribute_name(:completed_on) %></th>
      <th><%= model_class.human_attribute_name(:update) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each_with_index do |task, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= task.desc %></td>
        <td><%= task.status %></td>
        <td><%= task.created_at.to_date %></td>
        <td>
          <% if task.status.downcase == "complete" %>
            <%= task.updated_at.to_date %>
          <% else %>
            -
          <% end %>
        </td>
        <td>
          <% if task.status.downcase == "complete" %>
            <%= link_to 'Active', task_active_path(task), :class => 'btn btn-default btn-xs'  %>
          <% else %>
            <%= link_to 'Complete', task_complete_path(task), :class => 'btn btn-default btn-xs'  %>
          <% end %>
        </td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_task_path(task), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      task_path(task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_task_path,
            :class => 'btn btn-primary' %>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:desc) %>:</strong></dt>
  <dd><%= @task.desc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @task.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @task.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tasks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_path(@task), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_path(@task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>